export const states = {
    AL: { name: "Alabama", reps: 7 },
    AK: { name: "Alaska", reps: 1 },
    AZ: { name: "Arizona", reps: 9 },
    AR: { name: "Arkansas", reps: 4 },
    CA: { name: "California", reps: 52 },
    CO: { name: "Colorado", reps: 8 },
    CT: { name: "Connecticut", reps: 5 },
    DE: { name: "Delaware", reps: 1 },
    FL: { name: "Florida", reps: 28 },
    GA: { name: "Georgia", reps: 14 },
    HI: { name: "Hawaii", reps: 2 },
    ID: { name: "Idaho", reps: 2 },
    IL: { name: "Illinois", reps: 17 },
    IN: { name: "Indiana", reps: 9 },
    IA: { name: "Iowa", reps: 4 },
    KS: { name: "Kansas", reps: 4 },
    KY: { name: "Kentucky", reps: 6 },
    LA: { name: "Louisiana", reps: 6 },
    ME: { name: "Maine", reps: 2 },
    MD: { name: "Maryland", reps: 8 },
    MA: { name: "Massachusetts", reps: 9 },
    MI: { name: "Michigan", reps: 13 },
    MN: { name: "Minnesota", reps: 8 },
    MS: { name: "Mississippi", reps: 4 },
    MO: { name: "Missouri", reps: 8 },
    MT: { name: "Montana", reps: 2 },
    NE: { name: "Nebraska", reps: 3 },
    NV: { name: "Nevada", reps: 4 },
    NH: { name: "New Hampshire", reps: 2 },
    NJ: { name: "New Jersey", reps: 12 },
    NM: { name: "New Mexico", reps: 3 },
    NY: { name: "New York", reps: 26 },
    NC: { name: "North Carolina", reps: 14 },
    ND: { name: "North Dakota", reps: 1 },
    OH: { name: "Ohio", reps: 15 },
    OK: { name: "Oklahoma", reps: 5 },
    OR: { name: "Oregon", reps: 6 },
    PA: { name: "Pennsylvania", reps: 17 },
    RI: { name: "Rhode Island", reps: 2 },
    SC: { name: "South Carolina", reps: 7 },
    SD: { name: "South Dakota", reps: 1 },
    TN: { name: "Tennessee", reps: 9 },
    TX: { name: "Texas", reps: 38 },
    UT: { name: "Utah", reps: 4 },
    VT: { name: "Vermont", reps: 1 },
    VA: { name: "Virginia", reps: 11 },
    WA: { name: "Washington", reps: 10 },
    WV: { name: "West Virginia", reps: 2 },
    WI: { name: "Wisconsin", reps: 8 },
    WY: { name: "Wyoming", reps: 1 },
}

export const territories = {
    AS: { name: "American Samoa", reps: 1 },
    GU: { name: "Guam", reps: 1 },
    MP: { name: "Northern Mariana Islands", reps: 1 },
    PR: { name: "Puerto Rico", reps: 1 },
    VI: { name: "U.S. Virgin Islands", reps: 1 },
}

export const dc = {
    DC: { name: "District of Columbia", reps: 1 },
}